"""
RedShell :: AI Analyst Module
--------------------------------
Uses the Anthropic Claude API to:
  1. Summarize raw scan output (recon + CVE + web findings) into a plain-
     English executive summary.
  2. Risk-score and prioritize findings, with suggested remediation steps.

Requires an ANTHROPIC_API_KEY environment variable. If not set, falls
back to a deterministic rule-based summarizer so the rest of the app
still works for a live demo without API access.
"""

import os
import json
from typing import Optional

try:
    import anthropic
    _HAS_ANTHROPIC_SDK = True
except ImportError:
    _HAS_ANTHROPIC_SDK = False

MODEL = "claude-sonnet-4-6"


def _get_client():
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key or not _HAS_ANTHROPIC_SDK:
        return None
    return anthropic.Anthropic(api_key=api_key)


def _rule_based_fallback(recon_data: dict, cve_data: list, web_data: dict) -> dict:
    """Deterministic fallback when no API key is configured — keeps the
    demo fully functional offline."""
    open_count = len(recon_data.get("open_ports", [])) if recon_data else 0
    critical_cves = [c for c in (cve_data or []) if c.get("severity") == "CRITICAL"]
    web_findings = web_data.get("findings", []) if web_data else []
    critical_web = [f for f in web_findings if f.get("severity") == "CRITICAL"]

    risk_level = "LOW"
    if critical_cves or critical_web:
        risk_level = "CRITICAL"
    elif open_count > 5 or len(web_findings) > 5:
        risk_level = "HIGH"
    elif open_count > 0 or web_findings:
        risk_level = "MEDIUM"

    summary_lines = [
        f"Target exposed {open_count} open port(s)." if recon_data else "No recon data available.",
        f"{len(cve_data or [])} potential CVE(s) matched against detected services, {len(critical_cves)} rated CRITICAL." if cve_data else "No CVE data available.",
        f"{len(web_findings)} web application finding(s) identified, {len(critical_web)} rated CRITICAL." if web_data else "No web scan data available.",
    ]

    priorities = []
    for c in critical_cves[:3]:
        priorities.append(f"Patch/mitigate {c['cve_id']} affecting {c['matched_service']} on port {c['matched_port']}.")
    for f in critical_web[:3]:
        priorities.append(f"Remediate: {f['title']}.")
    if not priorities:
        priorities.append("No critical issues found — maintain current baseline and re-scan periodically.")

    return {
        "overall_risk": risk_level,
        "executive_summary": " ".join(summary_lines),
        "top_priorities": priorities,
        "ai_powered": False,
        "note": "Generated by rule-based fallback (no ANTHROPIC_API_KEY configured). Set the environment variable for full AI analysis.",
    }


def analyze_findings(recon_data: Optional[dict] = None, cve_data: Optional[list] = None,
                       web_data: Optional[dict] = None) -> dict:
    """
    Sends consolidated scan results to Claude for a plain-English summary,
    risk scoring, and prioritized remediation guidance. Falls back to a
    rule-based summary if no API key is available.
    """
    client = _get_client()
    if client is None:
        return _rule_based_fallback(recon_data, cve_data, web_data)

    payload = {
        "recon": recon_data or {},
        "cve_matches": cve_data or [],
        "web_findings": (web_data or {}).get("findings", []),
    }

    system_prompt = (
        "You are a senior security analyst reviewing automated scan output from an "
        "authorized penetration test / security assessment tool called RedShell. "
        "Given structured JSON scan data (network recon, matched CVEs, and web "
        "application findings), produce a concise executive risk summary. "
        "Respond ONLY with valid JSON, no markdown fences, no preamble, matching "
        "exactly this schema: "
        '{"overall_risk": "LOW|MEDIUM|HIGH|CRITICAL", '
        '"executive_summary": "2-4 sentence plain English summary for a non-technical stakeholder", '
        '"top_priorities": ["ordered list of the 3-5 most important remediation actions, each one sentence"], '
        '"technical_notes": "1-3 sentences of technical detail for the security team"}'
    )

    try:
        response = client.messages.create(
            model=MODEL,
            max_tokens=1024,
            system=system_prompt,
            messages=[
                {"role": "user", "content": f"Scan data:\n{json.dumps(payload, indent=2)[:12000]}"}
            ],
        )
        raw_text = "".join(block.text for block in response.content if hasattr(block, "text"))
        cleaned = raw_text.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
        parsed = json.loads(cleaned)
        parsed["ai_powered"] = True
        return parsed
    except Exception as e:
        fallback = _rule_based_fallback(recon_data, cve_data, web_data)
        fallback["note"] = f"AI analysis failed ({e}); showing rule-based fallback."
        return fallback


def chat_about_results(question: str, context: dict) -> str:
    """
    Optional: lets the user ask free-form questions about their scan
    results via the dashboard ('why is this CVE critical?', etc).
    """
    client = _get_client()
    if client is None:
        return "AI chat requires an ANTHROPIC_API_KEY to be configured on the server. Set it as an environment variable and restart RedShell."

    system_prompt = (
        "You are a security analyst assistant inside the RedShell dashboard. "
        "Answer the user's question about their scan results concisely and "
        "accurately, using only the provided scan context. If the answer isn't "
        "in the data, say so rather than guessing."
    )
    try:
        response = client.messages.create(
            model=MODEL,
            max_tokens=600,
            system=system_prompt,
            messages=[
                {"role": "user", "content": f"Scan context:\n{json.dumps(context, indent=2)[:10000]}\n\nQuestion: {question}"}
            ],
        )
        return "".join(block.text for block in response.content if hasattr(block, "text"))
    except Exception as e:
        return f"AI chat error: {e}"
